### ISSUE TITLE
Nearly half of driver data, interval data and pitstops not working.

### ISSUE THREAD

**Issue by Pedre117** [br-g/openf1#36] opened 2024-03-24 09:15 UTC
Whilst trying to retrieve data for the latest race I have come to notice that team color, team name, country code, first name, last name, interval data and pitstops aren't working properly. The driver data related fields are "none" for everyone, and the other two return an empty json when called.

**Comment by applecake1green** [comment] 2024-03-24 12:28
Yeah, experiencing this issue too. Try to develop a way that you can set a session_key to, as the latest one with **_functional_** (from what i can see) data is 9480 and the meeting_key is 1230.

**Comment by PrestonHager** [comment] 2024-04-13 05:31
Can you share exactly what data you are getting versus what data you expect to find. Please also include which URL you are gathering data from including any filtering.

**Comment by Pedre117** [comment] 2024-04-13 21:06
The URL `https://api.openf1.org/v1/drivers?session_key=latest` is returning this kind of data for all 20 drivers (I will only include Verstappen as the 'None' field issue is exactly the same for all the others) `{'session_key': 9496, 'meeting_key': 1232, 'broadcast_name': 'M VERSTAPPEN', 'country_code': None, 'first_name': None, 'full_name': 'Max VERSTAPPEN', 'headshot_url': None, 'last_name': None, 'driver_number': 1, 'team_colour': None, 'team_name': None, 'name_acronym': 'VER'}`. 
The URL `https://api.openf1.org/v1/pit?session_key=latest` returns an empty JSON instead of all of the session's pitstop timings (the only session for which something is returned is number 9158, but even then the timings are most likely wrong as they are in the hundreds of seconds). 
The URL `https://api.openf1.org/v1/intervals?session_key=latest` also returns an empty JSON instead of all of a session's intervals. The latest working session for the driver data and the intervals I've found is session number 9480

**Comment by PrestonHager** [comment] 2024-04-15 20:33
I believe this is a duplicate of issue #42 and #43. There is a pull request open to fix it #55, however, it only fixes future content. If you need a fix right now, I suggest downloading the fork/branch of that PR and running an instance locally until it merges and the previous data is re-ingested.

**Comment by br-g** [comment] 2024-05-01 16:40
Hello,
Thank you for reporting these bugs.
I believe they have all been fixed now!

**Closed by br-g** 2024-05-01 16:40 UTC
