### ISSUE TITLE
Driver Table Multiple Rows For Driver, Meeting & Session

### ISSUE THREAD

**Issue by rich-howell** [br-g/openf1#43] opened 2024-03-30 08:57 UTC
In the drivers table there seems to be two rows for the same `driver_key`,`meeting_key` & `session_key` with some of the information like `team_name` and `headshot_url` missing from one row but not the other.

### Example 
- driver_key = 77
- meeting_key = 1229
- session_key = 9466

This can be seen in the CSV file 

![image](https://github.com/br-g/openf1/assets/22135084/da9197b6-5ae8-46d9-b8ac-011fae5f4844)

Aswell as the returned JSON from the endpoint `https://api.openf1.org/v1/drivers?driver_number=77&meeting_key=1229&session_key=9466`

![image](https://github.com/br-g/openf1/assets/22135084/248bc3c9-c2d9-4dd2-a394-53c7a61df27b)

**Comment by PrestonHager** [comment] 2024-04-13 05:35
Data is being duplicated during the ingestor phase. Each driver has two database entries, one with correct data and one with data missing. This could be a possible duplicate of #42 or maybe an extension of that issue. Best fix for the client would be to filter or merge any duplicate data to throw away nulls.

**Comment by br-g** [comment] 2024-04-19 16:14
Fixed! Thanks for reporting the issue 👍

**Closed by br-g** 2024-04-19 16:14 UTC
